name: prestinv
description: "Application de gestion d'inventaire"
publish_to: 'none'

version: 1.3.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  intl: ^0.19.0 # Ajouté pour le formatage des nombres
  cupertino_icons: ^1.0.2
  dart_ping: ^9.0.1
  pdf: ^3.11.0
  printing: ^5.12.0
  path_provider: ^2.1.3
  share_plus: ^9.0.0

  # CORRECTION : On déplace le package ici
  flutter_native_splash: ^2.4.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  # La ligne était ici, elle a été déplacée dans la section dependencies ci-dessus

# ... Le reste du fichier (flutter: et flutter_native_splash:) ne change pas

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#002D42"
  image: assets/images/icon.png
  android: true
  ios: true